# Material Analysis

## Imports

### NumPy
- `import numpy as np`

#### Description:
NumPy is a powerful Python library for numerical computing. It provides support for multidimensional arrays, mathematical functions to operate on these arrays efficiently, and tools for working with arrays.

### Tabulate
- `from tabulate import tabulate`

#### Description:
Tabulate is a Python library used for creating formatted tables from data in Python. It simplifies the process of generating tables for display or output in various formats, including plain text, LaTeX, and HTML.

### SAnTex Material
- `from santex import Material`

#### Description:
The `Material` class from the Sage library is used for defining and working with materials calculations.

In [1]:
import numpy as np
from tabulate import tabulate
from santex import Material

## Function: `availablePhases`

### Description:
This function retrieves information about the available phases in the `Material` instance.

### Returns:
- `phases_info` (list): A list containing information about the available phases.

### Usage Example:
```python
material_instance = Material()
phases_info = material_instance.availablePhases()
print("Available Phases:")
print(phases_info)


In [2]:
material_instance = Material()
phases_info = material_instance.availablePhases()
print("Available Phases:")
print(phases_info)

Available Phases:
+---------------------------------------+---------------------+-----------------------------------+
|                 Phase                 |   Crystal System    |           Primary Phase           |
+---------------------------------------+---------------------+-----------------------------------+
|           Almandine-pyrope            |        Cubic        |              Garnet               |
|               Grossular               |        Cubic        |              Garnet               |
|               Majorite                |        Cubic        |              Garnet               |
|                Pyrope                 |        Cubic        |              Garnet               |
|              a_quartz_1               | Hexagonal/ Trigonal |              Quartz               |
|              a_quartz_2               | Hexagonal/ Trigonal |              Quartz               |
|              a_Quartz_3               | Hexagonal/ Trigonal |              Quart

## Function: `availablePrimaryPhases`

### Description:
This function retrieves information about the available primary phases in the `Material` instance.

### Returns:
- `primary_phases_info` (list): A list containing information about the available primary phases.

### Usage Example:
```python
material_instance = Material()
primary_phases_info = material_instance.availablePrimaryPhases()
print("Available Primary Phases:")
print(primary_phases_info)


In [3]:
# availablePrimaryPhases
primary_phases_info = material_instance.availablePrimaryPhases()
print("Available Primary Phases:")
print(primary_phases_info)
print()

Available Primary Phases:
+-----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|           Primary Phase           |                                                                Crystal Systems                                                                 |                                                                                                                                                 Phases                                                                                                                                                  |
+-----------

## Function: `availableCrystalSystems`

### Description:
This function retrieves information about the available crystal systems in the `Material` instance.

### Returns:
- `crystal_systems_info` (list): A list containing information about the available crystal systems.

### Usage Example:
```python
material_instance = Material()
crystal_systems_info = material_instance.availableCrystalSystems()
print("Available Crystal Systems:")
print(crystal_systems_info)


In [4]:
# availableCrystalSystems
crystal_systems_info = material_instance.availableCrystalSystems()
print("Available Crystal Systems:")
print(crystal_systems_info)
print()

Available Crystal Systems:
+---------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|   Crystal System    |                                                                                                                                                                                                                                              Phases                                                                                                                                                                                                      

## Material Instance Operations

### Description:
This section demonstrates operations performed on a `Material` instance.

### Usage Example:
```python
material_instance = Material()


We first check the properties of Almandine-Pyrope by invoking method ```get_properties_by_phase()``` and then will get the voigt stiffness matrix at pressure = 3GPa and Temp = 1000K for Diopside by invoking ```voigthighPT()``` method of the Material class

In [5]:
material_instance = Material()

# Get properties for 'Almandine-pyrope'
almandine_properties = material_instance.get_properties_by_phase('Almandine-pyrope')
print("Material Properties for Almandine-pyrope:")
print(tabulate(almandine_properties.items(), headers=["Property", "Value"], tablefmt="fancy_grid"))
print("\n")

# Get voigt matrix for 'Amphobole #3 Taramite-Tschermakite1'
non_isotropic_phase = 'Diopside'
non_isotropic_voigt_matrix = material_instance.get_voigt_matrix(non_isotropic_phase)
print(f'Voigt matrix for {non_isotropic_phase}:')
print(tabulate(non_isotropic_voigt_matrix, tablefmt="pretty"))

non_isotropic_phase = 'Diopside'
non_isotropic_voigt_matrix = material_instance.voigthighPT(non_isotropic_phase, 3, 1000)
print(f'Voigt matrix for {non_isotropic_phase}:')
print(tabulate(non_isotropic_voigt_matrix, tablefmt="pretty"))

Material Properties for Almandine-pyrope:
╒═════════════════════════╤═══════════════════════╕
│ Property                │ Value                 │
╞═════════════════════════╪═══════════════════════╡
│ Crystal System          │ Cubic                 │
├─────────────────────────┼───────────────────────┤
│ Primary Phase           │ Garnet                │
├─────────────────────────┼───────────────────────┤
│ Phase                   │ Almandine-pyrope      │
├─────────────────────────┼───────────────────────┤
│ Density(g/cm3)          │ 4.131                 │
├─────────────────────────┼───────────────────────┤
│ C11                     │ 306.7                 │
├─────────────────────────┼───────────────────────┤
│ C22                     │ 306.7                 │
├─────────────────────────┼───────────────────────┤
│ C33                     │ 306.7                 │
├─────────────────────────┼───────────────────────┤
│ C44                     │ 94.9                  │
├─────────────────────

In [6]:
non_isotropic_voigt_matrix

array([[239.17,  89.22,  85.69,   0.  ,   7.65,   0.  ],
       [ 89.22, 186.15,  65.15,   0.  ,   9.57,   0.  ],
       [ 85.69,  65.15, 232.06,   0.  ,  54.07,   0.  ],
       [  0.  ,   0.  ,   0.  ,  75.25,   0.  ,  10.83],
       [  7.65,   9.57,  54.07,   0.  ,  71.37,   0.  ],
       [  0.  ,   0.  ,   0.  ,  10.83,   0.  ,  80.81]])

## Get voigt matrix for forsterite

Lets now look at the voigt matrix that is obtained from the catalogue for phase Forsterite

In [7]:
material = Material()
material.get_voigt_matrix("Forsterite")

array([[320.5,  68.1,  71.6,   0. ,   0. ,   0. ],
       [ 68.1, 196.5,  76.8,   0. ,   0. ,   0. ],
       [ 71.6,  76.8, 233.5,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,  64. ,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,  77. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,  78.7]])

## Get voigt matrix and density for for diopside, enstatite, forsterite at high p and t

Lets load the stiffness tensors and density at any different P and T

In [9]:
material.voigthighPT('Forsterite', PRESSURE = 2, TEMP = 1500)

array([[297.72,  64.96,  71.44,   0.  ,   0.  ,   0.  ],
       [ 64.96, 175.9 ,  79.5 ,   0.  ,   0.  ,   0.  ],
       [ 71.44,  79.5 , 211.92,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,  52.88,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,  64.72,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,  65.32]])

In [10]:
material.voigthighPT('Enstatite', PRESSURE = 3, TEMP = 1500)

array([[227.78,  75.07,  52.31,   0.  ,   0.  ,   0.  ],
       [ 75.07, 168.71,  70.15,   0.  ,   0.  ,   0.  ],
       [ 52.31,  70.15, 217.74,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,  75.72,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,  71.6 ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,  70.95]])

In [11]:
material.voigthighPT('Diopside', PRESSURE = 3, TEMP = 1500)

array([[225.77,  83.47,  80.39,   0.  ,   8.25,   0.  ],
       [ 83.47, 175.8 ,  60.2 ,   0.  ,  10.07,   0.  ],
       [ 80.39,  60.2 , 219.36,   0.  ,  55.12,   0.  ],
       [  0.  ,   0.  ,   0.  ,  71.1 ,   0.  ,  12.93],
       [  8.25,  10.07,  55.12,   0.  ,  66.22,   0.  ],
       [  0.  ,   0.  ,   0.  ,  12.93,   0.  ,  74.76]])

Lets load density of Forsterite at ambient pressure and temperature

In [12]:
material.load_density("Forsterite")

3355.0

Lets now look at the density of the Forsterite at Pressure = 2GPa and Temperature = 1500K

In [13]:
material_instance.load_density("Forsterite", 2, 1500)

3098.6089636963993

Lets now look at the density of the Diopside at Pressure = 2GPa and Temperature = 1500K

In [14]:
material_instance.load_density("Diopside", 2, 1500)

3156.5123590988196

Lets now look at the density of the Enstatite at Pressure = 2GPa and Temperature = 1500K

In [15]:
material_instance.load_density("Enstatite", 2, 1000)

3167.7389007248685