In [1]:
import numpy as np
import pandas as pd

from satex import Tensor

In [2]:
cij_forsterite = np.array([[320.5,  68.15,  71.6,     0,     0,     0],
  [ 68.15,  196.5,  76.8,     0,     0,     0],
  [  71.6,   76.8, 233.5,     0,     0,     0],
  [   0,      0,      0,     64,     0,     0],
  [   0,      0,      0,      0,    77,     0],
  [   0,      0,      0,      0,     0,  78.7]])

cij_enstatite = np.array([[  236.90,   79.60,   63.20,    0.00,    0.00,    0.00],
  [    79.60,  180.50,   56.80,    0.00,    0.00,    0.00],
  [    63.20,   56.80,  230.40,    0.00,    0.00,    0.00],
  [     0.00,    0.00,    0.00,   84.30,    0.00,    0.00],
  [     0.00,    0.00,    0.00,    0.00,   79.40,    0.00],
  [     0.00,    0.00,    0.00,    0.00,    0.00,   80.10]])
cij_diopside = np.array([[  228.10,   78.80,   70.20,    0.00,    7.90,    0.00],
  [    78.80,  181.10,   61.10,    0.00,    5.90,    0.00],
  [    70.20,   61.10,  245.40,    0.00,   39.70,    0.00],
  [     0.00,    0.00,    0.00,   78.90,    0.00,    6.40],
  [     7.90,    5.90,   39.70,    0.00,   68.20,    0.00],
  [     0.00,    0.00,    0.00,    6.40,    0.00,   78.10]])

In [3]:
tensor = Tensor()

In [4]:
cijkl_forsterite = tensor.voigt_to_tensor(cij_forsterite)

In [5]:
cijkl_forsterite

array([[[[320.5 ,   0.  ,   0.  ],
         [  0.  ,  68.15,   0.  ],
         [  0.  ,   0.  ,  71.6 ]],

        [[  0.  ,  78.7 ,   0.  ],
         [ 78.7 ,   0.  ,   0.  ],
         [  0.  ,   0.  ,   0.  ]],

        [[  0.  ,   0.  ,  77.  ],
         [  0.  ,   0.  ,   0.  ],
         [ 77.  ,   0.  ,   0.  ]]],


       [[[  0.  ,  78.7 ,   0.  ],
         [ 78.7 ,   0.  ,   0.  ],
         [  0.  ,   0.  ,   0.  ]],

        [[ 68.15,   0.  ,   0.  ],
         [  0.  , 196.5 ,   0.  ],
         [  0.  ,   0.  ,  76.8 ]],

        [[  0.  ,   0.  ,   0.  ],
         [  0.  ,   0.  ,  64.  ],
         [  0.  ,  64.  ,   0.  ]]],


       [[[  0.  ,   0.  ,  77.  ],
         [  0.  ,   0.  ,   0.  ],
         [ 77.  ,   0.  ,   0.  ]],

        [[  0.  ,   0.  ,   0.  ],
         [  0.  ,   0.  ,  64.  ],
         [  0.  ,  64.  ,   0.  ]],

        [[ 71.6 ,   0.  ,   0.  ],
         [  0.  ,  76.8 ,   0.  ],
         [  0.  ,   0.  , 233.5 ]]]])

In [6]:
cij_forsterite = tensor.tensor_to_voigt(cijkl_forsterite)

In [7]:
cij_forsterite

array([[320.5 ,  68.15,  71.6 ,   0.  ,   0.  ,   0.  ],
       [ 68.15, 196.5 ,  76.8 ,   0.  ,   0.  ,   0.  ],
       [ 71.6 ,  76.8 , 233.5 ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,  64.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,  77.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,  78.7 ]])

# Rotate Tensors

In [8]:
alpha = 10
beta = 20
gamma = 30 # in degrees

In [9]:
rotated_forsterite = tensor.rotate_tensor(cijkl_forsterite, alpha, beta, gamma)

In [10]:
rotated_forsterite

array([[[[254.40669486,  32.19107185,   9.1917399 ],
         [ 32.19107185,  83.60527452,   2.25426383],
         [  9.1917399 ,   2.25426383,  74.25170921]],

        [[ 32.19107185,  93.02059007,   5.79247342],
         [ 93.02059007,  24.85704921,   6.26816834],
         [  5.79247342,   6.26816834,  -1.68082112]],

        [[  9.1917399 ,   5.79247342,  73.39492984],
         [  5.79247342,   4.15506621,   7.02836206],
         [ 73.39492984,   7.02836206,   4.58001959]]],


       [[[ 32.19107185,  93.02059007,   5.79247342],
         [ 93.02059007,  24.85704921,   6.26816834],
         [  5.79247342,   6.26816834,  -1.68082112]],

        [[ 83.60527452,  24.85704921,   4.15506621],
         [ 24.85704921, 229.09177813,   3.16662267],
         [  4.15506621,   3.16662267,  77.9967799 ]],

        [[  2.25426383,   6.26816834,   7.02836206],
         [  6.26816834,   3.16662267,  72.58824371],
         [  7.02836206,  72.58824371,  -5.76818554]]],


       [[[  9.1917399 ,   5.79

In [11]:
voigt_rotated_forsterite = tensor.tensor_to_voigt(rotated_forsterite)

In [12]:
pd.DataFrame(voigt_rotated_forsterite)

0           1           2          3          4          5
0  254.406695   83.605275   74.251709   2.254264   9.191740  32.191072
1   83.605275  229.091778   77.996780   3.166623   4.155066  24.857049
2   74.251709   77.996780  228.394000  -5.768186   4.580020  -1.680821
3    2.254264    3.166623   -5.768186  72.588244   7.028362   6.268168
4    9.191740    4.155066    4.580020   7.028362  73.394930   5.792473
5   32.191072   24.857049   -1.680821   6.268168   5.792473  93.020590